name:                 bookxml
version:              0.1.0.0
visibility:           public
id:                   bookxml-0.1.0.0-FHUnpP8Ze1K5uS5lfQRw3i
key:                  bookxml-0.1.0.0-FHUnpP8Ze1K5uS5lfQRw3i
license:              BSD-3-Clause
copyright:            2026 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/bookxml#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/bookxml#readme>

abi:                  ce0fd9383d105f094cfc3fb95da20e89
exposed:              True
exposed-modules:      Catalogue Lib
hidden-modules:       Paths_bookxml
import-dirs:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/lib/aarch64-osx-ghc-9.10.3-fe9c/bookxml-0.1.0.0-FHUnpP8Ze1K5uS5lfQRw3i

library-dirs:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/lib/aarch64-osx-ghc-9.10.3-fe9c/bookxml-0.1.0.0-FHUnpP8Ze1K5uS5lfQRw3i

library-dirs-static:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/lib/aarch64-osx-ghc-9.10.3-fe9c/bookxml-0.1.0.0-FHUnpP8Ze1K5uS5lfQRw3i

dynamic-library-dirs:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/lib/aarch64-osx-ghc-9.10.3-fe9c

data-dir:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/share/aarch64-osx-ghc-9.10.3-fe9c/bookxml-0.1.0.0

hs-libraries:         HSbookxml-0.1.0.0-FHUnpP8Ze1K5uS5lfQRw3i
depends:
    base-4.20.2.0-754f conduit-1.3.6.1-CJl0cF1RtfKDDtWNDXJqgk
    containers-0.7-a685 text-2.1.3-c55a
    xml-conduit-1.10.1.0-DQ3owDpWWalAFS2Cf4nAa4

haddock-interfaces:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/doc/bookxml-0.1.0.0/bookxml.haddock

haddock-html:
    /Users/maireadmeagher/Documents/GitRepos/fun-prog-26/dev/bookxml/.stack-work/install/aarch64-osx/699bc101a2efba1d088491ab518ec08329981f8317a31bdb9e1d4643382fd2a7/9.10.3/doc/bookxml-0.1.0.0
